### ISSUE TITLE
Initial data dump

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#1]
Just wanted to let you know that I uploaded data to your google drive for phase I. Please see the spreadsheet and let me know if you have any questions or concerns. This should have lat/long data for all 3367 of our buildings. Eventually we will want to refresh some of the metrics here, but this should allow you to start exploring the data.
 
Thanks, Terry

https://drive.google.com/open?id=0Bz0jVhHV5wowMUJFSHJjd0Uxbzg

**Comment by almccon** [comment]
Dumped to a CSV (which I checked into this repo).

Also pushed the CSV to a new CARTO account, and made a quick visualization:

https://cityenergy-seattle.carto.com/builder/571fad64-b8ea-11e6-8314-0ef24382571b/embed

<img width="1166" alt="screen shot 2016-12-02 at 2 dec 4 28 05" src="https://cloud.githubusercontent.com/assets/1212178/20854866/62da087c-b8ac-11e6-8acb-2021c31c3e4e.png">


Table on CARTO is here:
https://cityenergy-seattle.carto.com/dataset/table_2015_stamen_phase_i

Here are the columns they provided, plus a list of the future column names that are not include in this dump:

| Metric Name                                                                       | Phasing | Shared with Stamen? | Variable Name          |              |    |     |                  | 
|-----------------------------------------------------------------------------------|---------|---------------------|------------------------|--------------|----|-----|------------------| 
| City of Seattle Benchmarking building ID                                          | 1       | Yes                 | ID                     |              |    |     |                  | 
| "City of Seattle Building Type (NR,  MF,  K-12,  Campus,  Muni etc.)" | 1  | Yes | BuildingTypeName | 
| Primary Property Type - EPA Calculated                                            | 1       | Yes                 | PropertyTypeEPA        |              |    |     |                  | 
| Property Name                                                                     | 1       | Yes                 | BuildingName           |              |    |     |                  | 
| Address                                                                           | 1       | Yes                 | Address                |              |    |     |                  | 
| City                                                                              | 1       | Yes                 | City                   |              |    |     |                  | 
| State                                                                             | 1       | Yes                 | State                  |              |    |     |                  | 
| Zip                                                                               | 1       | Yes                 | Zip                    |              |    |     |                  | 
| Neighborhood Area                                                                 | 1       | Yes                 | Neighborhood           |              |    |     |                  | 
| Latitude                                                                          | 1       | Yes                 | Latitude               |              |    |     |                  | 
| Longitude                                                                         | 1       | Yes                 | Longitude              |              |    |     |                  | 
| Year Built                                                                        | 1       | Yes                 | YearBuilt              |              |    |     |                  | 
| Property GFA EPA calculated (Building(s)) (ft²)                                   | 1       | Yes                 | GrossFloorAreaQuantity |              |    |     |                  | 
| Number of Buildings                                                               | 1       | Yes                 | NumBuildings           |              |    |     |                  | 
| Number of Floors                                                                  | 1       | Yes                 | NumFloors              |              |    |     |                  | 
| Number of Units (MF)                                                              | 1       | Yes                 | NumUnits               |              |    |     |                  | 
| ENERGY STAR Score                                                                 | 1       | Yes                 | ES_Score               |              |    |     |                  | 
| Site EUI (kBtu/ft²)                                                               | 1       | Yes                 | SiteEUI                |              |    |     |                  | 
| Source EUI (kBtu/ft²)                                                             | 1       | Yes                 | SourceEUI              |              |    |     |                  | 
| Total GHG Emissions (Metric Tons CO2e) (Regional Grid)                            | 1       | Yes                 | TotalGHGEmissionsReg   |              |    |     |                  | 
| GHG Emissions Intensity (kg CO2e/ft2)                                             | 1       | Yes                 | GHGEmissionsIntensity  |              |    |     |                  | 
| Weather Normalized Source EUI (kBtu/ft²)                                          | 2       | No                  |                        |              |    |     |                  | 
| Weather Normalized Site EUI (kBtu/ft²)                                            | 2       | No                  |                        |              |    |     |                  | 
| Site Total Energy Use (kBtu)                                                      | 2       | No                  |                        |              |    |     |                  | 
| Weather Normalized Site Total Energy Use (kBtu)                                   | 2       | No                  |                        |              |    |     |                  | 
| ENERGY STAR Certification - Year(s) Certified                                     | 2       | No                  |                        |              |    |     |                  | 
| District Steam Use (klbs steam)                                                   | 2       | No                  |                        |              |    |     |                  | 
| Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kWh) | 2       | No                  |                        |              |    |     |                  | 
| Natural Gas Use (therms)                                                          | 2       | No                  |                        |              |    |     |                  | 
| Electricity Use – Generated from Onsite Renewable Systems (kWh)                   | 2       | No                  |                        |              |    |     |                  | 
| Default Values Used for Space Details (Y/N)                                       | 2       | No                  |                        |              |    |     |                  | 
| Building Outline Shapefile                                                        | 2       | No                  |                        |              |    |     |                  | 
| Portfolio Manager Property ID                                                     | 2       | No                  |                        |              |    |     |                  | 
| Council District                                                                  | 2       | No                  |                        |              |    |     |                  | 
| "Open ""comments"" field for owners/managers to provide information"              | 2       | No                  |                        |              |    |     |                  | 
| Number of Bedrooms - Multifamily                                                  | 2       | No                  |                        |              |    |     |                  | 
| Total Seattle GHG Emissions (Seattle City Light Factors)                          | 2       | No                  |                        |              |    |     |                  | 
| Low Outlier by property type (Y/N)                                                | 2       | No                  |                        |              |    |     |                  | 
| High Outlier by property type (Y/N)                                               | 2       | No                  |                        |              |    |     |                  | 
| Compliance Status (Y/N)                                                           | 2       | No                  |                        |              |    |     |                  | 
| "Seattle ENERGY STAR Performance by building (Poor,  Fair,  Good,  Excellent)"           | 2            | No |     |                  | 
| Year over year performance changes                                                | 3       | No                  |                        |              |    |     |                  | 
| Annual Total Est. Energy Costs                                                    | 3       | No                  |                        |              |    |     |                  | 
| Percent Improvement Potential Energy Cost Savings                                 | 3       | No                  |                        |              |    |     |                  | 
| All Other Fuels (kBtu)                                                            | 3       | No                  |                        |              |    |     |                  |

**Comment by almccon** [comment]
I manually changed the column names after they were uploaded to CARTO. Instead I need to update the `doee_scripts` folder to transform the column names programmatically for future updating. See #19.
