### ISSUE TITLE
Source of GFA

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#10]
GFA, # of Reported buildings – do we need to provide this data or does Stamen calculate?

**Comment by emilyhobson** [comment]
@almccon Can you ask @sconnelley about source of GFA?

**Comment by almccon** [comment]
Gross Floor Area? It was provided in the first Seattle data dump.

**Comment by almccon** [comment]
Both Gross Floor Area and Number of Buildings are included in the Seattle data. We don't need to calculate them.
