### ISSUE TITLE
Parcel zooms

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#101]
Why only show building outlines (vs dots) only at zoom=15 or greater? You showed us a map of LA with parcels/building outlines that looked great with the shapes. Happy to discuss pros/cons/

**Comment by sconnelley** [comment]
@emilyhobson @almccon -- I just arbitrarily picked that zoom level.  Do we want to always show them? If not, what zoom level should it be set to?

**Comment by nicolettehayes** [comment]
![screen shot 2017-09-05 at 10 32 28 am](https://user-images.githubusercontent.com/12550451/30074211-863a1b56-9225-11e7-8931-41f1ca43abb7.png)
