### ISSUE TITLE
Citywide Report 2015 data representation

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#104]
Are we getting Citywide data for 2015? Because if not, we should suppress the "Change from last year" section so it doesn't show a (surely) inaccurate 100% increase:

![screen shot 2017-08-18 at 2 17 29 pm](https://user-images.githubusercontent.com/12550451/29478282-f44e508e-8420-11e7-9c0f-89f64fb43a03.png)

**Comment by nicolettehayes** [comment]
![screen shot 2017-09-05 at 11 39 44 am](https://user-images.githubusercontent.com/12550451/30076789-f303ae1a-922e-11e7-8b0e-af9eabd17079.png)

**Comment by sconnelley** [comment]
Waiting on citywide change data from client.  It will be static data that will be placed in the config file.

**Comment by sconnelley** [comment]
Showing a message when user is trying to view "Change from Last Year" chart when there is no data for the previous year.  Could use some stylistic touches @nicolettehayes. 

![image](https://user-images.githubusercontent.com/565486/30923009-c69ab2c8-a378-11e7-80c5-46e980d764c2.png)
