### ISSUE TITLE
No data representation

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#107]
The terms "infinity" "NaN" and "0" are used, which it makes it hard to interpret. 

It would be great to assign "error" and "N/A" to make it a little clearer whether we're talking about bad data or a lack of data.

![screen shot 2017-08-21 at 2 12 47 pm](https://user-images.githubusercontent.com/12550451/29538707-d0096a8a-867b-11e7-92f2-f256cea257da.png)
-
![screen shot 2017-08-21 at 2 13 09 pm](https://user-images.githubusercontent.com/12550451/29538708-d0fdd8fe-867b-11e7-86b6-b1605eb9ad92.png)
-
![screen shot 2017-08-21 at 2 12 23 pm](https://user-images.githubusercontent.com/12550451/29538712-d5774334-867b-11e7-9209-dddbaaa2347c.png)
-
![screen shot 2017-08-21 at 2 11 22 pm](https://user-images.githubusercontent.com/12550451/29538718-db917fb4-867b-11e7-8de2-122919753d09.png)
-
![screen shot 2017-08-21 at 2 10 19 pm](https://user-images.githubusercontent.com/12550451/29538723-dd7a99f0-867b-11e7-8e22-6408030e2503.png)

**Comment by nicolettehayes** [comment]
![screen shot 2017-09-05 at 10 58 23 am](https://user-images.githubusercontent.com/12550451/30075246-24abf450-9229-11e7-8586-59ba7ee7d1fa.png)

**Comment by sconnelley** [comment]
**COMPARED TO AVERAGE**

**No EUI data**
![image](https://user-images.githubusercontent.com/565486/30923089-faf2fbc0-a378-11e7-8863-bbeb72de3b17.png)

**No Energy score**
![image](https://user-images.githubusercontent.com/565486/30923143-19090870-a379-11e7-9dd4-b92f80f3db32.png)

**No data at all for Energy Star score**
![image](https://user-images.githubusercontent.com/565486/30923315-8cdedc7a-a379-11e7-93d8-f8205e595a37.png)

**Comment by sconnelley** [comment]
**FUEL USE**

**No emissions**
![image](https://user-images.githubusercontent.com/565486/30923200-334b6732-a379-11e7-9ad2-c42cd975111b.png)
