### ISSUE TITLE
redundant or inaccurate labelling in Fuel Use

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#108]
In the Fuel Use section, I'm trying to figure out if this indicates "a million million":
![screen shot 2017-08-21 at 2 35 28 pm](https://user-images.githubusercontent.com/12550451/29539297-1e23abca-867e-11e7-95ce-c2e3b6151f10.png)

Here it is in context:
![screen shot 2017-08-21 at 2 35 22 pm](https://user-images.githubusercontent.com/12550451/29539296-1e219eb6-867e-11e7-9fd0-e482da3c70bc.png)

**Comment by nicolettehayes** [comment]
![screen shot 2017-09-05 at 11 13 37 am](https://user-images.githubusercontent.com/12550451/30075654-44c3b9f6-922b-11e7-93b0-76ba2fdc6e4b.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/30933158-b9e296a8-a397-11e7-9781-d90f84d5876f.png)
