### ISSUE TITLE
flipped axis in scorecard? nope.

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#110]
I can't figure this one out...

Albertson's has one of the highest EUIs (I filtered the map to show just the worst properties):

![screen shot 2017-08-21 at 4 01 37 pm](https://user-images.githubusercontent.com/12550451/29541721-c4c361da-868a-11e7-940e-c51263b75823.png)

Yet, when I look at Albertson's scorecard, the histogram reflects the opposite!

![screen shot 2017-08-21 at 4 02 19 pm](https://user-images.githubusercontent.com/12550451/29541750-f4621152-868a-11e7-9572-cce5f65d3504.png)

Does it have something to do with how Albertson's compares to other grocery stores versus how it compares to all buildings?

![screen shot 2017-08-21 at 4 10 37 pm](https://user-images.githubusercontent.com/12550451/29541803-56e589c6-868b-11e7-849c-9cc4466d1899.png)

OH god. And did we decide that the color scale should be redrawn for the new histogram distribution once you select a property type? Because that is going to create some fundamental confusion, however much sense it makes on the surface.

compared to all buildings: ![screen shot 2017-08-21 at 4 14 24 pm](https://user-images.githubusercontent.com/12550451/29541888-f26ba0a6-868b-11e7-9d69-7a8102f2927f.png)
compared to grocery stores: ![screen shot 2017-08-21 at 4 14 57 pm](https://user-images.githubusercontent.com/12550451/29541887-f26ac960-868b-11e7-8d75-a07d5d31f441.png)

I guess that ties into #109 -- if we are going to change the color comparison, we also need to make the dots reflect the filtered dataset on the map.

OK, I get it. And now the coloring in the scorecard reflects that change and makes perfect sense:
![screen shot 2017-08-21 at 4 13 17 pm](https://user-images.githubusercontent.com/12550451/29541908-0b585276-868c-11e7-8563-6265890593c6.png)

So the problem here is about going from an all-building histogram to a property-type histogram without explicit buy-in from the user...

We may need to talk to the client to solve this one.

**Comment by sconnelley** [comment]
That was a bit weird.  I think I have it straightened out now, where the compare chart remains the same whether or not a property type is selected.

**Show all buildings**
![image](https://user-images.githubusercontent.com/565486/30709253-9f162596-9ecf-11e7-84ea-81533f1c4a30.png)

**Supermarket / Grocery**
![image](https://user-images.githubusercontent.com/565486/30709306-c3a4333a-9ecf-11e7-82be-21dbdc5d041d.png)
