### ISSUE TITLE
Show both 2015 and 2016

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#112]
![screen shot 2017-09-05 at 10 24 22 am](https://user-images.githubusercontent.com/12550451/30073922-6a439c8e-9224-11e7-8e49-0fae9b887e06.png)

**Comment by nicolettehayes** [comment]
feels connected to #53 and #102

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/30824686-55c259b4-a1fe-11e7-9fb2-28bf5c9aa123.png)
