### ISSUE TITLE
Update description for Site Total Energy Use

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#113]
![screen shot 2017-09-05 at 10 57 20 am](https://user-images.githubusercontent.com/12550451/30075205-ffe2f772-9228-11e7-8e32-66ea9f6bb88a.png)

Use this text:

Non-normalized site energy use is the total amount of all the energy a property consumes on-site annually, as reported on utility bills. Site energy use is measured in thousands of British thermal units (kBtu).

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/30605243-5cc60b88-9d3b-11e7-8771-73050c4b33ff.png)
