### ISSUE TITLE
Fuel Use 100% Electric bug

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#114]
It sounds like not all buildings with 100% electric fuel usage are being treated the same. I haven't found an example yet, but I'll keep looking.

Ultimately, they should all have a consistent treatment (show explanation text in the bar instead of just saying "100%):

![screen shot 2017-09-05 at 11 02 35 am](https://user-images.githubusercontent.com/12550451/30075369-b9e86f4e-9229-11e7-92ea-2cfa855827d0.png)

**Comment by nicolettehayes** [comment]
Example of problem:

https://cityenergyproject.github.io/seattle/#seattle/2016?layer=site_eui&sort=site_eui&order=desc&lat=47.60489&lng=-122.32907&zoom=13&building=357&report_active=true

![screen shot 2017-09-05 at 11 12 31 am](https://user-images.githubusercontent.com/12550451/30075612-26a8d67c-922b-11e7-99fb-0382e0289e6e.png)

**Comment by sconnelley** [comment]
This was fixed in #116.  It was due to issues with rounding percentages.  Smaller percentages like `0.000003` were being rounded to zero.
