### ISSUE TITLE
Fuel Use label bug

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#116]
On Seattle Municipal tower the "natural gas" label appears even though there is no natural gas used.

![screen shot 2017-09-05 at 11 11 36 am](https://user-images.githubusercontent.com/12550451/30075572-fc3c662e-922a-11e7-9fbb-1ba3861e1c11.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/30937033-a7637e64-a3a3-11e7-84de-9c7c6b2e7c2f.png)
