### ISSUE TITLE
New text section under Fuel Use

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#117]
Under the note about CO2E equivalency in Fuel Use, add this text:

The emissions values reported here use custom emissions factors provided by Seattle City Light and Enwave for electricity and steam, respectively. Natural gas calculations use a standard emissions factor from Portfolio Manager. Seattle City Light (SCL) secures carbon offsets equal to the greenhouse gas emissions resulting from all aspects of SCL’s operations, including those created by the generation of electricity the utility buys, employees’ travel, and the trucks and other equipment used in its operations.

![screen shot 2017-09-05 at 11 19 00 am](https://user-images.githubusercontent.com/12550451/30075880-0775e41a-922c-11e7-8c16-edcc3326f742.png)

**Comment by sconnelley** [comment]
@nicolettehayes - We will probably want to style the extra text a bit different `¯\_(ツ)_/¯`
![image](https://user-images.githubusercontent.com/565486/30823292-af68f784-a1f9-11e7-96f1-ad0a0446dc12.png)

**Comment by nicolettehayes** [comment]
Eek! So much text.

Let's left-align it in 10px type with 12px line-spacing. The gap between the CO2E text and this text looks good. But we'll have to left-align the CO2E text as well to make this work. 

<img width="743" alt="screen shot 2017-09-25 at 11 27 13 pm" src="https://user-images.githubusercontent.com/12550451/30842632-3342bf1e-a249-11e7-8e9c-9eeb9b0aef36.png">
