### ISSUE TITLE
Remove text in Energy Star header

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#118]
Remove the extra instances of the words "Energy Star" in the Energy Star.

![screen shot 2017-09-05 at 11 21 06 am](https://user-images.githubusercontent.com/12550451/30075967-4f323b82-922c-11e7-8bd0-bc384c09ac7e.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/30712936-b6a9c9e0-9edb-11e7-8ffe-af0e72416a47.png)
