### ISSUE TITLE
Add Energy Star Logo

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#119]
This would require an Energy Star Logo file:

![screen shot 2017-09-05 at 11 22 38 am](https://user-images.githubusercontent.com/12550451/30076039-88f79b14-922c-11e7-977a-4f84f9f7c8a0.png)

**Comment by nicolettehayes** [comment]
Here is the logo: https://drive.google.com/a/stamen.com/file/d/0B36c8E17SDHGUWEzc0g2cnpHc3M/view?usp=sharing

This is a little dicey. If we put it the certification inline on the graph, it will have to be pretty tiny and even then will risk creating unsightly situations.

If we go this route, here is a mock (with logo at 15px high, text in 8px with 8px line-spacing):

<img width="750" alt="screen shot 2017-09-25 at 11 10 50 pm" src="https://user-images.githubusercontent.com/12550451/30842301-05e12878-a247-11e7-8341-43d53d94c04d.png">

Alternatively, we could place the Certified stamp in the header of the building, which would have 3 benefits: 1) more room for messaging and making the logo a legible size 2) more resilient even with dynamic content and 3) the certification would be present whether the user selected Energy Star or EUI as their lens, making it even more visible. The only con would be that it eats up the white space (or in this case blue space?).

Here is a mock (with logo at 40px high, text in 12px with 14px line-spacing):

<img width="748" alt="screen shot 2017-09-25 at 11 16 37 pm" src="https://user-images.githubusercontent.com/12550451/30842481-2ad41edc-a248-11e7-87f0-d8b705e46a03.png">

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/30974036-9dabbd5c-a43c-11e7-9985-4a18feb631c0.png)

**Comment by sconnelley** [comment]
Temporarily showing the logo when a building has an energy score >= 75 while we wait for "certified" field to be added to the data. Once certified field is added to data, will need to update config with field name.
