### ISSUE TITLE
Final data set upload and  training 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#12]
final dataset will most likely be ready on the 2nd or 3rd week of January.  I’m sure all the development will be completed by then – does Stamen upload data or do you show CoS how to do?

**Comment by almccon** [comment]
Terry and I went through the whole process, and captured the steps in https://github.com/cityenergyproject/seattle/blob/master/UPDATING.md.

He will try at least one more data update on his own just to verify that knowledge has been transferred.
