### ISSUE TITLE
Revised Energy Star Histograms

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#120]
The Energy Star histogram distribution should be fixed across all bulidings: 10 for poor (1-50), 5 for fair (51-75), 3 for good (76-90) and 2 for excellent (91-100)

![screen shot 2017-09-05 at 11 24 12 am](https://user-images.githubusercontent.com/12550451/30076371-73024fd8-922d-11e7-915c-41d13a5abecd.png)

As opposed the how we show it now (8 for poor, 3 for fair, 2 for good, 8 for excellent):
![screen shot 2017-09-05 at 11 26 05 am](https://user-images.githubusercontent.com/12550451/30076392-7de0887a-922d-11e7-8e46-2fb47a0a71cf.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/30713152-59c843c2-9edc-11e7-9230-1c62f8866b2e.png)
