### ISSUE TITLE
Enhance the line in the Change from Last Year graph

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#121]
![screen shot 2017-09-05 at 11 34 56 am](https://user-images.githubusercontent.com/12550451/30076697-92aa7706-922e-11e7-9974-05af7a4f608b.png)

I can see implementing this in one of two ways: a) color the building line (at full opacity) to match the color of the most recent year, b) or color the building line (at full opacity) using a gradient that matches the years in question:

a)
![screen shot 2017-09-05 at 11 34 46 am](https://user-images.githubusercontent.com/12550451/30076694-8f294120-922e-11e7-9c04-4a52fb593eff.png)

b)
![screen shot 2017-09-05 at 11 38 08 am](https://user-images.githubusercontent.com/12550451/30076730-b57595ae-922e-11e7-9f47-73ca26d6a4aa.png)

**Comment by sconnelley** [comment]
Went with color option b:

![image](https://user-images.githubusercontent.com/565486/30824790-a52dd500-a1fe-11e7-9a27-3b4877df4360.png)
