### ISSUE TITLE
Links Section

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#122]
![screen shot 2017-09-05 at 11 42 00 am](https://user-images.githubusercontent.com/12550451/30077003-48710b2c-922f-11e7-98cc-e98a2ec522ba.png)

**Comment by sconnelley** [comment]
I was hoping modifying the template would be sufficient, https://github.com/cityenergyproject/seattle/blob/master/src/app/templates/scorecards/scorecard.html#L20-L40

**Comment by sconnelley** [comment]
Links data should be pulled from a Carto data table.

**Comment by sconnelley** [comment]
Added in commit be0e093b29d321cedfa3e7a6e34df82cd87e3680

The Carto table is `links`.
