### ISSUE TITLE
CARTO account - hand off 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#14]
Please use the following email address energybenchmarking@seattle.gov for the Carto account along with Terry Sullivan’s contact information – 206-684-8244. Address information is the same as my signature contact information below. If the account can’t be transferred to the City of Seattle, please let us know so we can establish one ourselves from scratch.

**Comment by almccon** [comment]
Email is now Terry's, and he has the password.

Password is still in Stamen's 1password for the time being.

**Comment by almccon** [comment]
Also, it's still a free account. https://cityenergy-seattle.carto.com
