### ISSUE TITLE
Scorecard PDF tweaks

### ISSUE THREAD

**Issue by vinaydixit** [cityenergyproject/seattle#141]
adjustments to formatting/styling of existing content when users print to PDF

OSE to outline proposed changes to formatting.

**Comment by ebrelsford** [comment]
Terry sent [these updates as PDF](https://github.com/cityenergyproject/seattle/files/3928442/scorecard.text.and.print.edits.to.stamen.pdf)

**Comment by ebrelsford** [comment]
What I'm gleaning from the annotated PDF:
 * [x] Add [YEAR] PERFORMANCE PROFILE to top right
 * [x] Make address and area bold
 * [x] Center header: delete text definition and make number fill the space (for both EUI and ENERGY STAR score). Link ENERGY STAR and EUI to glossary if possible.
 * [x] Energy star histogram: explore adding 1 / 100 to x axis
 * [x] Explore adding footer and Seattle Energy Benchmarking logo to footer of PDF
 * [x] Look into text behind text when printing
 * [x] Move Energy Use Trends chart above Fuel Use and Emissions

**Comment by seattle-benchmarking** [comment]
@ebrelsford That looks correct (along with other changes logged in other items). One correction: explore adding **1** / 100 to x axis

**Comment by ebrelsford** [comment]
@seattle-benchmarking Do you have a version of the icon for the print footer that we can use? The version we have is older.

**Comment by seattle-benchmarking** [comment]
![OSE_BENCH_LOGO_RGB](https://user-images.githubusercontent.com/58457382/70474271-257bd100-1a87-11ea-86c0-d2b79120fea5.png)

**Comment by seattle-benchmarking** [comment]
@ebrelsford  Here's a PNG file. I can publish to web and give you a URL if that's better.

**Comment by ebrelsford** [comment]
@seattle-benchmarking This is perfect, thanks!

**Comment by seattle-benchmarking** [comment]
@ebrelsford Three things I'm noticing in the scorecards on print to PDF:

- [x] All of the buildings with ENERGY STAR are going to 3 pages - can we discuss options for limiting to 2 pages? We talked about this a few weeks back and you mentioned limiting the height of some graphics. We can also hide the buttons on the WAYS TO SAVE section. 

- [x] When printing to PDF (using Chrome or Firefox with default print settings), a few things are getting cut off on the right edge. See images below.

- [x] I've seen a few bubbles from the emissions chart coming into the emissions legend. See below.

See example printing ID 26939
![image](https://user-images.githubusercontent.com/58457382/70952434-0a770700-201b-11ea-92cf-e82547d7203a.png)

![image](https://user-images.githubusercontent.com/58457382/70952439-0e0a8e00-201b-11ea-8511-fa522f9b3f0e.png)

![image](https://user-images.githubusercontent.com/58457382/70952443-119e1500-201b-11ea-8f54-298ead18c45a.png)


[printtopdf_26939.pdf](https://github.com/cityenergyproject/seattle/files/3970663/printtopdf_26939.pdf)

**Comment by ebrelsford** [comment]
@seattle-benchmarking I've fixed the overlaps that you pointed out on print.

I've also managed to get the pages down to two by rearranging the charts as discussed on our call. When there is no energy star score the other charts grow a bit to take advantage of the extra room.

Let me know what you think!
