### ISSUE TITLE
Back to Map

### ISSUE THREAD

**Issue by vinaydixit** [cityenergyproject/seattle#142]
Back to map is a confusing situation for the user -- we need to assess why they are 'leaving' that page if they aren't leaving the app itself. Amira to take a pass at a modal interaction first. At minimum we need a larger 'back' button and/or browser hack to enable the client's back button.

**Comment by ebrelsford** [comment]
I am working on looking at the back button functionality. It's certainly possible but a little tricky. Would take ~4 hours.
