### ISSUE TITLE
Map Page Search Box

### ISSUE THREAD

**Issue by vinaydixit** [cityenergyproject/seattle#144]
exact language TK from amira/eric, implement into mock/staging site for approval.

**Comment by ebrelsford** [comment]
I have added the Property ID to the autocomplete results as requested by Terry:

![image](https://user-images.githubusercontent.com/375002/70261909-52677580-1761-11ea-915f-7e563981f0ec.png)

**Comment by seattle-benchmarking** [comment]
@ebrelsford can you change from Property ID to Building ID?

**Comment by ebrelsford** [comment]
@seattle-benchmarking Yes, no problem.
