### ISSUE TITLE
Savings Opportunities Numbers

### ISSUE THREAD

**Issue by vinaydixit** [cityenergyproject/seattle#145]
Customers view savings opportunities as arbitrary and don't trust the numbers. restructure right side of header.

**Comment by seattle-benchmarking** [comment]
Amira is exploring minor formatting changes to COST OF ENERGY section per 12.16 discussion
![image](https://user-images.githubusercontent.com/58457382/71017511-7f921d00-20ab-11ea-95a0-8be88c749616.png)

**Comment by ebrelsford** [comment]
One option (make the line less wide):

![image](https://user-images.githubusercontent.com/375002/71121476-894f7980-21ac-11ea-8839-c5d63d6069d2.png)

Another option (horizontally orient numbers):

![image](https://user-images.githubusercontent.com/375002/71121886-59ed3c80-21ad-11ea-92d1-4a7d9f1d0b03.png)

**Comment by ebrelsford** [comment]
We went with the shortened line between the numbers.
