### ISSUE TITLE
Consider alternative to pie charts for Fuel Use & Emissions section 

### ISSUE THREAD

**Issue by vinaydixit** [cityenergyproject/seattle#148]
Amira to take a look and provide new solutions to address visibility and help clarify the relationship between gas and emissions in particular.

**Comment by ebrelsford** [comment]
Alternatives to pie charts we've explored before:

![image](https://user-images.githubusercontent.com/375002/70542047-16a02780-1b36-11ea-8a91-38419f8eb7ce.png)

![image](https://user-images.githubusercontent.com/375002/70542088-26b80700-1b36-11ea-96f9-0f0d2bb13ce3.png)

![image](https://user-images.githubusercontent.com/375002/70542099-2a4b8e00-1b36-11ea-8d42-2124696ff159.png)

![image](https://user-images.githubusercontent.com/375002/70542135-35062300-1b36-11ea-974c-426d4df351bc.png)

**Comment by aaamira** [comment]
I'm really liking the stacked bar chart direction (out of 100%) - the last one seems to work especially well. should we run these by the team again?

**Comment by seattle-benchmarking** [comment]
@aaamira We like the stacked bar chart as well, but still think changing colors is appropriate given the feedback we received. I think @ebrelsford was going to weigh in on the level of effort to change the type of graph.

**Comment by ebrelsford** [comment]
@aaamira I'm open to trying it and the effort isn't too high. Would you mind thinking through how the stacked bars would look with three energy sources? Here's [an example](https://cityenergyproject.github.io/seattle/#seattle/2018?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.60937&lng=-122.33388&zoom=14&building=19484&report_active=true):

![image](https://user-images.githubusercontent.com/375002/70574560-6270c200-1b72-11ea-879d-061ce04d6633.png)

I guess as long as we center the label over the usage % bar and keep the colors consistent it should be clear?

**Comment by seattle-benchmarking** [comment]
We changed last year to just use Gas instead of Natural Gas - which should help with spacing when there are three energy sources on the stacked bars

**Comment by aaamira** [comment]
@ebrelsford - sounds good! I'll take a look

**Comment by ebrelsford** [comment]
Moving this comment over from #147 (@seattle-benchmarking):

> Two comments from Rebecca on the new fuel use vs emissions bars:
> 1 - the yellow text is hard to read (steam). anything we can do about that? It's not too bad on screen but gets worse on print
> 2 - the bars feel different in style than the rest of the page, probably since so much of our other graphics use bold colors sparingly to highlight the building in question. but this whole graphic uses the bold colors. not sure this is necessarily bad but might explore either (a) reducing the height of the bar to minimize this feel or (2) use a slightly less bold version of the colors.
> 

![image](https://user-images.githubusercontent.com/375002/70749352-236d7880-1cfa-11ea-9e39-eedd7dce330b.png)

**Comment by seattle-benchmarking** [comment]
@ebrelsford  Seeing some issues with certain buildings that have three fuels:

- [ ] Three fuels issue with labels (https://cityenergyproject.github.io/seattle/#seattle/2018?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.65570&lng=-122.31242&zoom=14&building=29390&report_active=true)

![image](https://user-images.githubusercontent.com/58457382/70953268-87a37b80-201d-11ea-98f4-b9a91f6c9d4b.png)

**Comment by ebrelsford** [comment]
I deployed a fix for this. @seattle-benchmarking mind checking on it?

**Comment by seattle-benchmarking** [comment]
@ebrelsford Looks great! Can find any overlapping
