### ISSUE TITLE
Neighborhood and property type wraps

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#15]
Property type
1. Change category names to wrap elegantly OR
1. Make dropdown wider
 
Neighborhood
1. Change names to be shorter and/or
1. Standard capitalization 

![image](https://cloud.githubusercontent.com/assets/824082/21128384/70d46764-c0af-11e6-80b5-eacb6a2325d1.png)

**Comment by emilyhobson** [comment]
They are going to send over new data but let's make the font size smaller

**Comment by almccon** [comment]
I just tried changing the font size, but I ended up changing the font size everywhere else in the interface, too. Will spend more time to figure it out later, but won't let this block my first delivery of code today.

**Comment by almccon** [comment]
Latest data file includes much shorter names, so I don't think we need to change the display now. 

![screen shot 2017-01-08 at 8 jan 11 18 17](https://cloud.githubusercontent.com/assets/1212178/21759388/c51377d0-d5f8-11e6-8bac-1695eff82ae9.png)

**Comment by emilyhobson** [comment]
Terry is going to add spaces around the slashes
