### ISSUE TITLE
Update email template to send scorecards

### ISSUE THREAD

**Issue by ebrelsford** [cityenergyproject/seattle#153]
Terry sent this [document](https://github.com/cityenergyproject/seattle/files/3928449/Scorecard.Email.Content.Working.docx) for a desired email template.

**Comment by ebrelsford** [comment]
@seattle-benchmarking I've put some work into updating the macro, in this 
[zip file](https://github.com/cityenergyproject/seattle/files/3970318/updated-print-macro.zip). Mind trying it and letting us know how that looks?

**Comment by ebrelsford** [comment]
I will double-check the fields used in the CSV from the PDF generator and confirm that they are compatible with the email template.

**Comment by seattle-benchmarking** [comment]
@ebrelsford I did some basic testing just to send the email with the test case you gave me. Worked just fine. Let me know when you verify the fields and I will test the whole process end to end.

**Comment by ebrelsford** [comment]
@seattle-benchmarking I think we're looking good. I've updated the [instructions](https://docs.google.com/document/d/1xw71GXHNF-6y5XCYeB1DZwE-x6oR0IGqGCYhHQC8UVk/edit#) which includes a link to the updated Excel Macro and example.

**Comment by seattle-benchmarking** [comment]
@ebrelsford This looks great. Added a few minor clarifying notes to the instructions document but otherwise good to go.
