### ISSUE TITLE
Fix print on Microsoft Edge

### ISSUE THREAD

**Issue by ebrelsford** [cityenergyproject/seattle#155]
It doesn't look very good right now, part of that is some simple CSS, part of it is that Edge won't print background colors.

**Comment by ebrelsford** [comment]
This has been greatly improved in that the majority of the elements now appear in print on Edge. The biggest remaining issue is that Edge will not print background colors. For the most part this is okay, but you should see some of the issues in [this PDF made with Edge](https://github.com/cityenergyproject/seattle/files/3970311/edge-printed.pdf).

**Comment by seattle-benchmarking** [comment]
@ebrelsford Thanks - this looks much better. I'm seeing a lot of issues with the GHG bubble chart too - and the fuel vs GHG bar charts seem to never display. Is there anyway to show an error message when they print with Edge to encourage using a different browser?  similar to what we do with mobile - i think we tell them they should use a desktop. Or is it possible to hide the whole GHG section for Edge?

**Comment by ebrelsford** [comment]
@seattle-benchmarking What looks wrong on the GHG bubble chart? I'm looking at it in Edge and it looks fine.

I'm still working on the bar chart in fuel use and emissions as part of #148.

I'm not convinced the printing on Edge is bad enough that we should recommend a different browser.

**Comment by seattle-benchmarking** [comment]
![image](https://user-images.githubusercontent.com/58457382/71200714-6c1eb780-224d-11ea-9124-579383b84fc2.png)

**Comment by seattle-benchmarking** [comment]
When I print to PDF in Edge i see these lines across the bubbles

**Comment by ebrelsford** [comment]
Thanks for that @seattle-benchmarking, here's what I'm seeing when printing to PDF in Edge:

![image](https://user-images.githubusercontent.com/375002/71279853-c55b1980-2327-11ea-9f9e-3154302b1bbc.png)

Would you mind sharing the settings you used? And which version of Edge you're using?

**Comment by ebrelsford** [comment]
The bar charts should appear now when printing in Edge. On my test machine this looks pretty good--let me know how it works for you @seattle-benchmarking ?
