### ISSUE TITLE
Favicon default

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#16]
![image](https://cloud.githubusercontent.com/assets/824082/21128409/9594f1ae-c0af-11e6-94d9-da7837767888.png)

**Comment by emilyhobson** [comment]
https://github.com/cityenergyproject/seattle/tree/master/src/images/favicons

**Comment by almccon** [comment]
Fixed in fdad32ea2713f1dd3378f083fa05b1da7ad8ec74 and 66f7ca5186b88c5f5c4f063b8d22f2749611b5d8.

![screen shot 2017-01-06 at 6 jan 4 14 00](https://cloud.githubusercontent.com/assets/1212178/21737229/c957b244-d42b-11e6-8e3c-e0e26df50ab8.png)
