### ISSUE TITLE
Branding logo

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#2]
https://drive.google.com/open?id=0B5tBIGe_xerccDNyZk1ITEpFb081MDNndVRMT2QwTUVzRy1v

**Comment by almccon** [comment]
See 5fb4b068173f2870815e7c8631edef6a1280ec97

**Comment by almccon** [comment]
Latest plan is to remove header #40, since the application will be embedded within the chrome of another website. So this is moot.
