### ISSUE TITLE
Labels over dots 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#20]
https://cityenergyproject.github.io/seattle/#seattle/2015?categories[0][field]=primary_ptype_epa&categories[0][values][]=Data+Center&categories[0][other]=false&layer=energy_star_score&metrics[]=energy_star_score&sort=energy_star_score&order=desc&lat=47.65232213800995&lng=-122.3243522644043&zoom=13

Data center dot is under the neighborhood label

**Comment by almccon** [comment]
This is a CARTO feature, not a bug. But if we want we can switch to the labels underneath the dots.

**Comment by almccon** [comment]
<img width="672" alt="screen shot 2017-01-17 at 10 26 11 pm" src="https://cloud.githubusercontent.com/assets/1212178/22053211/12d01b24-dd04-11e6-9c42-e00e9d7cc946.png">
Done.
