### ISSUE TITLE
Mouseover color is hard to see

### ISSUE THREAD

**Issue by almccon** [cityenergyproject/seattle#22]
![seattle_mouseover_color](https://cloud.githubusercontent.com/assets/1212178/21574037/f62ff33e-cea0-11e6-9d63-8c78da8ec2f0.gif)

**Comment by emilyhobson** [comment]
That link blue is troublesome as well

**Comment by almccon** [comment]
Fixed the hover state. The default link blue is being superseded by the cartodb.css stylesheet, and I'm having trouble overriding it. Leaving it for now.
![mouseover_seattle](https://cloud.githubusercontent.com/assets/1212178/22054558/0aaabf24-dd0b-11e6-864c-036d650013bc.gif)
