### ISSUE TITLE
Reorder and change less/more cutoff on Property detail page

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#23]
Current: 
![image](https://cloud.githubusercontent.com/assets/824082/21629664/432d376e-d1df-11e6-844f-439f1c0c9483.png)

Desired:: 

![image](https://cloud.githubusercontent.com/assets/824082/21629675/607a55ea-d1df-11e6-82c5-e1284371ebc3.png)

**Comment by almccon** [comment]
![screen shot 2017-01-09 at 9 jan 12 07 07](https://cloud.githubusercontent.com/assets/1212178/21760268/9b8e955a-d5ff-11e6-9023-e9ed4b50deaf.png)
![screen shot 2017-01-09 at 9 jan 12 06 23](https://cloud.githubusercontent.com/assets/1212178/21760269/9ba3fabc-d5ff-11e6-949c-27b549a634ca.png)
Oh, and the Seattle Hebrew Academy is misspelled.
