### ISSUE TITLE
Year build color indicators missing

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#26]
https://cityenergyproject.github.io/seattle/#seattle/2015?layer=yearbuiltstring&metrics[]=energy_star_score&metrics[]=yearbuiltstring&metrics[]=reported_gross_floor_area&sort=yearbuiltstring&order=desc&lat=47.607465080615476&lng=-122.33598232269286&zoom=14

![image](https://cloud.githubusercontent.com/assets/824082/21629899/1adce726-d1e1-11e6-80fd-ec671f6b9476.png)

**Comment by almccon** [comment]
Dupe of #32
