### ISSUE TITLE
Internet Explorer - IE bugs

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#29]
version 11 and backwards
Hangs and never loads past the loading icon

**Comment by emilyhobson** [comment]
This loads now that the comparison table is removed. Once that comes back in the on-demand form, will need to re-test.

**Comment by emilyhobson** [comment]
Sony's new IE issues:

 
1.  Zooming in and out seems buggy.  When I click the Zoom In (+), the map shifts right instead of zooming in and when zooming back out, the maps do not render correctly.
1. The filters either don’t work or take a while to work (so it appears that they are not working).

**Comment by almccon** [comment]
Testing on IE11/Win7 (using VirtualBox) and I can't replicate the zoom-in/zoom-out bug.

Also, the filters work for me, but they are sometimes slow. However, I think it's the same slowness that happens on all platforms (see #33, #39)

**Comment by almccon** [comment]
Now that we re-enabled the comparison view (see #33), one of the IE bugs has come back: 

On IE 11, Win 7, on initial load the spinner just spins forever. The initial load never completes. 

Error: "Object doesn't support property or method 'find'" on line 316 in building_comparison.js.
`building = buildings.find(function(b) { return b.get(buildingId) == currentBuilding; }),`

Needs a polyfill: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find
