### ISSUE TITLE
Skyline or other 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#3]
1. Here's an FPO skyline @almccon 
https://drive.google.com/open?id=0B5tBIGe_xercZXJSNGp6Tlg5V2c

2. They want us to draw a new one but let's drop this into the platform to start. 
Nico should draw one using this image as reference: https://drive.google.com/open?id=0B5tBIGe_xercTTUzZGJGRm93emhDNm9idjZkRmxfZzUwYXJj

**Comment by almccon** [comment]
See 5fb4b068173f2870815e7c8631edef6a1280ec97

**Comment by nicolettehayes** [comment]
options...

![skyline-seattle-short](https://cloud.githubusercontent.com/assets/12550451/21123370/11cb0ff6-c08d-11e6-9d0b-915d54e991fa.png)
![skyline-seattle-test](https://cloud.githubusercontent.com/assets/12550451/21123371/11cd0a7c-c08d-11e6-80bf-fede747fc1e4.png)
![skyline-seattle](https://cloud.githubusercontent.com/assets/12550451/21123372/11ce1e26-c08d-11e6-9470-d8f1b74e7a58.png)

**Comment by nicolettehayes** [comment]
in the new color:

![skyline-seattle-0047ba](https://cloud.githubusercontent.com/assets/12550451/21202865/0ce6e202-c205-11e6-841b-aff6bf81477b.jpg)

**Comment by emilyhobson** [comment]
Send this file to Sony, @nicolettehayes

**Comment by nicolettehayes** [comment]
email sent


![ce-seattle-skyline](https://cloud.githubusercontent.com/assets/12550451/21825116/3aa3b34a-d737-11e6-8324-26026a730c2b.png)

<img width="342" alt="ce-seattle-skyline 2x" src="https://cloud.githubusercontent.com/assets/12550451/21825117/3aaa63f2-d737-11e6-9d92-269050194baf.png">

**Comment by nicolettehayes** [comment]
closing this since it seems they were satisfied.
