### ISSUE TITLE
Redesign property popup for readability 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#31]
Because the content is so dense, it's increasingly hard to read as parameters are being added. Redesign for readability.

**Comment by nicolettehayes** [comment]
The best fix for this would be to actually organize the content with headers, as well as applying some additional styling:

Short version:
![ce-seattle-popup-artboard 4](https://cloud.githubusercontent.com/assets/12550451/21822940/181e41d6-d72e-11e6-9f02-dac8ada38f31.jpg)

Long version:
![ce-seattle-popup-artboard 3](https://cloud.githubusercontent.com/assets/12550451/21822943/1b3440c8-d72e-11e6-8a7f-3877d18af20f.jpg)

Notice the "long version" is so long that a solution would be required: probably either to scroll or to show different "pages" of content.

If we decide to implement I can draw up some redlines to specify the line heights, spacing and weights that make for the best legibility possible.

**Comment by nicolettehayes** [comment]
closing in favor of #48
