### ISSUE TITLE
property type dropdown double scroll bars 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#34]
![image](https://cloud.githubusercontent.com/assets/824082/21665696/66205832-d2a2-11e6-9c06-3fd3a3557288.png)

**Comment by almccon** [comment]
Fixed and tested in Chrome and Safari
![scrollbars](https://cloud.githubusercontent.com/assets/1212178/22050767/85d6cd28-dcf2-11e6-8842-8d3c797757c9.gif)
