### ISSUE TITLE
Tweak default grey to be darker, possibly colder

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#35]
panel on the left and text headers on the table
Consider making higher constrast globally and possibly be more harmonious with grey used on map

**Comment by almccon** [comment]
Currently the panel on the left is defined here: https://github.com/cityenergyproject/seattle/blob/master/src/styles/main/_filter.scss#L134
`@include linear-gradient(to right, #dedede, #d0d0d0);`

The text seems to be #d1d1d0 from here: https://github.com/cityenergyproject/seattle/blob/master/src/styles/base/_variables.scss#L21

If we try to match the map, here are a few colors to try:
#a4afb0 is the dark gray of the coastline in the basemap.
#cdd2d4 is the blue-gray of the ocean on the map

Option 1 is #a4afb0
<img width="1031" alt="screen shot 2017-01-17 at 9 22 02 pm" src="https://cloud.githubusercontent.com/assets/1212178/22052057/84774732-dcfc-11e6-8073-a59cd8e492ee.png">

Option 2 is #cdd2d4
![screen shot 2017-01-17 at 9 33 01 pm](https://cloud.githubusercontent.com/assets/1212178/22052064/923f8afa-dcfc-11e6-9a38-2292976a747f.png)

Option 3 is just darkening the existing gray, which I think works better:
<img width="1048" alt="darkening the existing gray" src="https://cloud.githubusercontent.com/assets/1212178/22052448/2d30269e-dcff-11e6-9d74-f9d9e6189987.png">

Option 4 is the same as Option 3, but I'm darkening the pop-up, too. I think that makes the popup harder to see, however.
<img width="1029" alt="darkening the existing gray and popup" src="https://cloud.githubusercontent.com/assets/1212178/22052469/4d228ea6-dcff-11e6-9b63-7ba37fcf5839.png">

Going to implement Option 3 for now.
