### ISSUE TITLE
6 / 7 - Design of  revisions of comparison table

### ISSUE THREAD

**Issue by almccon** [cityenergyproject/seattle#39]
The building list is the primary cause of the slowness in #33. Also, almost nobody uses it and most people don't even know it's there.

We should not load it by default. Instead, there should be a button you click to "show building comparison".

While it's loading, there should be a spinner gif.

Bonus enhancement: we could add pagination to this list.

**Comment by almccon** [comment]
I narrowed down the slowness to this part of the code: https://github.com/cityenergyproject/seattle/blob/a11e35c1f54732c49324770eb99112d29e86fed6/src/app/views/building_comparison/building_comparison.js#L36-L55

**Comment by almccon** [comment]
We need to delay running that part of the code until the users requests to view the building comparison list.

**Comment by almccon** [comment]
It seems that the slowness occurs anytime you choose a new metric (one that hasn't been calculated before). It's the loop inside updateMetrics [here](https://github.com/cityenergyproject/seattle/blob/a11e35c1f54732c49324770eb99112d29e86fed6/src/app/views/building_comparison/building_comparison.js#L36-L55) that's the problem.
Once the building-by-building metrics have been calculated for a metric, it's fast to switch back and forth between already-calculated metrics. But once you choose one that hasn't been calculated, you get the 10-12 second slowness again.

So that's another argument why we need to fully refactor the comparison list into its own view, so it can go ahead and take as long as it needs to refresh, without blocking the map pane. Currently, both panes are part of the same view.

**Comment by emilyhobson** [comment]
1.  select _n_ specific buldings to compare (via search selection?)
2.  compare types 
3. compare types in a region (council, hood, )

**Comment by nicolettehayes** [comment]
first draft

![cep-building comp2](https://cloud.githubusercontent.com/assets/12550451/23634950/ec69a02e-0281-11e7-9418-f9ba2598cf6e.png)

**Comment by nicolettehayes** [comment]
This is also where citywide metrics will live, bumping up the time to make this holistic enough to cover all needs of numbers 6 & 7 in the discovery doc.

**Comment by nicolettehayes** [comment]
![cep-0502-comparison copy](https://cloud.githubusercontent.com/assets/12550451/26424208/48aa7796-4085-11e7-8daf-28c8be9fb596.jpg)
![cep-0502-comparison](https://cloud.githubusercontent.com/assets/12550451/26424209/48b5ba0c-4085-11e7-91ec-b99c05ef2439.jpg)
