### ISSUE TITLE
Edits to slider end caps

### ISSUE THREAD

**Issue by almccon** [cityenergyproject/seattle#43]
A few of the slider end caps need to be modified.

Property size low end from 0 to 20,000 (since no buildings under that size exist in our data)
ENERGY STAR Score end point from 100+ to 100 (can’t have a higher score than 100)
Cap lower end Source EUI at 0
With the new data, the GHG end points will need to be adjusted:
Low end for Total Emissions = 0
High end for Total Emissions = 500
Low end for GHG Intensity = 0
High end for GHG Intensity = 10

**Comment by almccon** [comment]
All fixed, with the exception of Source EUI. I have the lower end set at 0, but I think the fact that the low end is a negative number (-2) is confusing the override. It seems similar to #21, but not exactly the same.

**Comment by emilyhobson** [comment]
Fixed?

**Comment by almccon** [comment]
No, Source EUI is still mysteriously broken, and I haven't figured out why.
