### ISSUE TITLE
3 - Design of building pane

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#48]
Including viz with 
Building-level visualization displaying: 

- District Steam Use (kBtu) 
- Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kBtu) 
- Natural Gas Use (kBtu) 
- Other (kBtu

**Comment by nicolettehayes** [comment]
![screen shot 2017-05-24 at 1 26 02 pm](https://cloud.githubusercontent.com/assets/12550451/26424000/8defe526-4084-11e7-976e-4d2a15bd264c.png)
