### ISSUE TITLE
Design of Scorecard 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#49]

**Comment by nicolettehayes** [comment]
![cep-scorecard-highresscorecard 300x-100](https://cloud.githubusercontent.com/assets/12550451/26424034/ae5f568e-4084-11e7-8503-a9216b329b91.jpg)

![cep-0502-scorecard-cot1](https://cloud.githubusercontent.com/assets/12550451/26424070/cf7005bc-4084-11e7-8cc4-09a4c8192cea.jpg)
![cep-0502-scorecard-cot2](https://cloud.githubusercontent.com/assets/12550451/26424072/cf7cb4ba-4084-11e7-8f0c-ad68f170c7fc.jpg)
![cep-0502-scorecard-icons](https://cloud.githubusercontent.com/assets/12550451/26424074/d255aab6-4084-11e7-889c-8b23d85d60da.jpg)
![cep-0502-scorecard-mocked copy](https://cloud.githubusercontent.com/assets/12550451/26424093/de0ca4ae-4084-11e7-85e5-349431301860.jpg)
![cep-0502-scorecard-mocked_1](https://cloud.githubusercontent.com/assets/12550451/26424094/de114e32-4084-11e7-8270-f07c9336981f.jpg)
![cep-0502-scorecard-mocked](https://cloud.githubusercontent.com/assets/12550451/26424098/e33787d2-4084-11e7-813c-b705b24091f6.jpg)
![cep-0502-scorecard-noemissions](https://cloud.githubusercontent.com/assets/12550451/26424109/e52982f2-4084-11e7-828e-9d1964ef56d4.jpg)
