### ISSUE TITLE
Color ramps - add green

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#5]
For divergent coloring schemes, we’d like Seattle Blue to represent ‘good’ – so high ENERGY STAR scores and low EUIs. Our preference would be to have one of our reds (#9e3d22) as the other anchor to the Seattle Blue. In the past, we’ve used blue and red with some orange in between when reporting (see our [dashboard  ](https://public.tableau.com/profile/seattle.benchmarking#!/vizhome/EnergyBenchmarkingDashboard2015/EnergyBenchmarkingDashboard2015)for example). We’re not necessarily wed to this but I think some intermediary colors would be nice.

For the neutral coloring schemes, we like that you have a separate pallet for D.C. and L.A., but I don’t think we love those particular colors. Can you try to find something that works well with the Red – Blue divergent?

**Comment by almccon** [comment]
Using @nicolettehayes first suggestion for now: #3666b4  to #e7ba2e  to #9e3d22

**Comment by almccon** [comment]
<img width="318" alt="screen shot 2016-12-12 at 12 dec 4 29 17" src="https://cloud.githubusercontent.com/assets/1212178/21122614/2a44fd76-c088-11e6-8037-ce765e1f6bf5.png">

**Comment by nicolettehayes** [comment]
and for the neutral: 

#800180 to #028b8b 

![screen shot 2016-12-12 at 4 46 34 pm](https://cloud.githubusercontent.com/assets/12550451/21123351/fc25ceca-c08c-11e6-8aec-4352666ac175.png)

**Comment by almccon** [comment]
Using #3e4b84 as the midpoint for that.

<img width="314" alt="screen shot 2016-12-12 at 12 dec 6 02 21" src="https://cloud.githubusercontent.com/assets/1212178/21124670/2aa30e4a-c095-11e6-9e52-bfaf54360608.png">
<img width="318" alt="screen shot 2016-12-12 at 12 dec 6 02 12" src="https://cloud.githubusercontent.com/assets/1212178/21124671/2aa941c0-c095-11e6-822c-2429962eb5bb.png">

**Comment by nicolettehayes** [comment]
#f0e5c7  to #007749 

and

#1f5dbe  to #ffd552  to #ab2328  



![screen shot 2016-12-14 at 1 50 36 pm](https://cloud.githubusercontent.com/assets/12550451/21202907/37a9ac0e-c205-11e6-9132-af0f087e2251.png)

**Comment by emilyhobson** [comment]
need to green to the bottom one to avoid the greyish since that's NA

**Comment by nicolettehayes** [comment]
with the bottom three chopped off it looks like this:

#007749 to #b8cba9

![screen shot 2017-01-09 at 4 25 21 pm](https://cloud.githubusercontent.com/assets/12550451/21789223/3f3d7846-d688-11e6-8ee2-b24521007d1a.png)

**Comment by nicolettehayes** [comment]
To add a green midpoint to the left, I also added an orange placeholder midpoint to the right:

#1f5dbe to **#599B67** to #ffd552 to to **#DA863F** to #ab2328

![screen shot 2017-01-09 at 4 40 19 pm](https://cloud.githubusercontent.com/assets/12550451/21789522/86f9cd36-d68a-11e6-8d45-c30237a190d2.png)

**Comment by almccon** [comment]
Before:
![screen shot 2017-01-09 at 9 jan 6 17 17](https://cloud.githubusercontent.com/assets/1212178/21791493/fb64dc3a-d697-11e6-9f20-9e3de742f51e.png)
After:
![screen shot 2017-01-09 at 9 jan 6 17 23](https://cloud.githubusercontent.com/assets/1212178/21791496/005414a4-d698-11e6-9c1d-369201977dce.png)
Cartographically, I'm starting to cringe. Maybe there's some way to make the no-data gray color more distinct, so we don't have to use the full rainbow here?

**Comment by almccon** [comment]
For the green only, ramp, here's before:
![screen shot 2017-01-09 at 9 jan 6 24 30](https://cloud.githubusercontent.com/assets/1212178/21791635/fc1e2e3c-d698-11e6-883b-6c098c423e5b.png)
And after:
![screen shot 2017-01-09 at 9 jan 6 24 35](https://cloud.githubusercontent.com/assets/1212178/21791639/014cc044-d699-11e6-84a8-c1974475c638.png)

**Comment by nicolettehayes** [comment]
I totally agree Alan, the rainbow makes me miserable. It's like a child's birthday party instead of visualizing city energy data... But that's what happens when you fix red to one end, and blue to the other, and have to use colors from the client's brand guidelines. :/
