### ISSUE TITLE
3 - Building detail pane, viz build

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#51]
Inclusion of Building-level visualization 

District Steam Use (kBtu) 
Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kBtu) 
Natural Gas Use (kBtu) 
Other (kBtu)

**Comment by almccon** [comment]
See prototype vis of fuel use by type in #64

**Comment by sconnelley** [comment]
@emilyhobson @almccon @nicolettehayes Where is this "detail" pane going, the map building popup?

**Comment by emilyhobson** [comment]
Correct - it's the map building popup

**Comment by sconnelley** [comment]
**Design**
![image](https://user-images.githubusercontent.com/565486/27093476-d83dd8d0-5034-11e7-968e-2d680fcf4025.png)

**Comment by nicolettehayes** [comment]
No longer relevant, because it is housed on the scorecard:

"Inclusion of Building-level visualization

District Steam Use (kBtu)
Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems (kBtu)
Natural Gas Use (kBtu)
Other (kBtu)"

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/28428361-32dfd8d6-6d47-11e7-9cf5-a90b847ad726.png)
