### ISSUE TITLE
5 - additional years 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#53]
Add new data in end of July. Test.

**Comment by almccon** [comment]
Should be easy, given that the DC site and other sites include multiple year data, but some of our data views will need to be enhanced/built with multi-year comparisons in mind. For example, #59

**Comment by sconnelley** [comment]
Currently set up to use one table to handle multiple years.  There is a `year` column for setting the year value.
The table I am currently using is `table_2015_stamen_phase_ii_v2_w_year`
