### ISSUE TITLE
6 & 7 - Building and category compare - build - 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#54]
Select building types to compare 
Select specific buildings to compare  
Display comparative Building EUI Quartile, Energy Star, and Median EUI 

a. Median Site EUI by property type 
b. Median Year Built by property type 
c. Median size by property type 
d. Median EPA ENERGY STAR score by property type 
e. ENERGY STAR Performance by building (Poor, Fair, Good, Excellent) 
f. Median EUI by Property Type 
g. Total Reported Energy Use by Fuel Source (entire dataset) 
h. Total Reported GHG Emissions (entire dataset)

**Comment by emilyhobson** [comment]
@sconnelley can you estimate this based on Nico's new designs?

**Comment by sconnelley** [comment]
@emilyhobson - is this the latest design?

![image](https://user-images.githubusercontent.com/565486/27090594-9ef7b784-502b-11e7-844b-f66b28604187.png)
