### ISSUE TITLE
7 - Citywide metrics build

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#55]
1. Citywide Metrics  
2. Building type/citywide  
a.  Filters for building type, neighborhood

**Comment by emilyhobson** [comment]
from Seattle - We’ve talked about two ways to deal with these metrics: 
1. A separate interface with a dynamic table and/or other citywide charts, or 
2. Incorporating these into the current interface along the lines of what Nicolette has started with the LA example. We’re open to ideas on either option.

**Comment by almccon** [comment]
See a data sketch in #65

**Comment by sconnelley** [comment]
@emilyhobson or @nicolettehayes can someone confirm this design is what I am building here?

![cep-0502-scorecard citywide](https://user-images.githubusercontent.com/565486/27090717-fcec87fc-502b-11e7-81d6-d6dbdf8eed1d.jpg)
