### ISSUE TITLE
8 - Additional search fields 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#57]
Search option enhancements: 

By Building ID  
By all addresses (including alternative addresses)

**Comment by sconnelley** [comment]
Can now search by `property_id` field.  There were no other address fields to use, so couldn't do anything about that.  I am not showing `property_id` field in the search result list but we can change that.  
Moved some of the search config to the city config file, so if you want to add more search terms, you can do it here: https://github.com/cityenergyproject/seattle/blob/scorecard/src/cities/seattle.json#L29-L45
