### ISSUE TITLE
9 - Score card build 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#58]
Score cards with 
static and dynamic data, and 
filtering interactivity (toggles) for each building with display of: 

1. Year over year performance changes 
2. Annual Total Est. Energy Costs by building 
3. Percent Improvement 
4. Potential Energy Cost Savings 
5. Subset of building detail metrics including: 
6. Portfolio Manager Property ID 
7. Weather Normalized Site Total Energy Use (kBtu) 
8. Total Seattle GHG Emissions (Seattle City Light Factors) 
9. Electricity Use – Generated from Onsite Renewable Systems (kWh) 
10. Default Value flag and Outlier Data flag 
11. ENERGY STAR Certification - Year(s) Certified

**Comment by sconnelley** [comment]
@emilyhobson is #67 the same issue?

**Comment by sconnelley** [comment]
@nicolettehayes how are these scorecards accessed?

**Comment by sconnelley** [comment]
**current state**
![image](https://cloud.githubusercontent.com/assets/565486/25978184/c6050068-368e-11e7-9c5f-babda0a63b16.png)

**Comment by sconnelley** [comment]
design in #66

**Comment by emilyhobson** [comment]
Per terry: I don’t see a percent change variable for EUI in the data – so please compute. To clarify, this graph should use site_eui_wn instead of site_eui.
