### ISSUE TITLE
Primary Color

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#6]
Primary color - #003DA5 – “Seattle Blue”

**Comment by almccon** [comment]
Note to self and @sconnelley: see all the spots in c9a7a7db9d114207a37eb5a15b53867fea55321e where you have to change colors. That should all go in one spot, probably.

**Comment by almccon** [comment]
> Hello Emily, Nicolette and Alan,
> Here is a link to the color palette that we have adopted for the City of Seattle Web site, http://www9.seattle.gov/redesign/styleguide/ Please swap out the Seattle blue on the benchmarking vis site prior to packaging up code if possible. Perhaps you will find additional options for the color bands within these web guideline. There is another font option listed as well Open Sans. Per the header guideline, you can start to explore what may work with the site title. Our web designer has started mocking up options and it looks like the Office of Sustainability and Environment will be part of the web banner above the site. I feel confident that you can remove the OSE logo from the vis site banner.
> Thanks,
> Rebecca

The primary blue in that styleguide is #0047ba. So I'll use that instead of #003da5. 

There are many other colors in that style guide which are potentially useful for #5.
