### ISSUE TITLE
9 - Compare building scorecard year to year design

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#61]
For single building

**Comment by nicolettehayes** [comment]
![cep-0502-scorecard-cot1](https://cloud.githubusercontent.com/assets/12550451/26424184/30bfba06-4085-11e7-98d6-ea495e74613d.jpg)
![cep-0502-scorecard-cot2](https://cloud.githubusercontent.com/assets/12550451/26424183/30befff8-4085-11e7-8e31-287e2912ad07.jpg)
