### ISSUE TITLE
D3 prototype of fuel use data

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#64]
it would be great to see this brought to life:

<img width="191" alt="screen shot 2017-04-03 at 1 23 00 pm" src="https://cloud.githubusercontent.com/assets/12550451/24630291/f6d11f88-1870-11e7-925a-5a6cc5ce3f9a.png">

**Comment by almccon** [comment]
Done here: http://studio.stamen.com/cityenergy/show/energyuse.html
481b350e61fd4e9e89264c2bba45ce7dee41c30c

**Comment by almccon** [comment]
![screen shot 2017-04-07 at 7 apr 10 43 33](https://cloud.githubusercontent.com/assets/1212178/24881275/29eafd72-1df2-11e7-8600-75b6a331b245.png)
