### ISSUE TITLE
D3 prototype of EUI (kBTU/sf)

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#65]
Not completely sure what this needs to looks like... maybe a single bar chart for all buildings, and then call out the citywide average for all buildings, the citywide average for a couple building types, and a couple of specific building data.

<img width="474" alt="screen shot 2017-04-03 at 1 26 32 pm" src="https://cloud.githubusercontent.com/assets/12550451/24630512/d49cfcba-1871-11e7-9409-ae20102af98d.png">

Bonus would be to get some clarity on the whole change over time issue (i.e. how many years, which ones, if more years are coming, etc.)

<img width="462" alt="screen shot 2017-04-03 at 1 26 39 pm" src="https://cloud.githubusercontent.com/assets/12550451/24630553/f4bce578-1871-11e7-8bc3-685ebca4bda7.png">

**Comment by almccon** [comment]
my proudest work:
![screen shot 2017-04-03 at 3 apr 8 27 28](https://cloud.githubusercontent.com/assets/1212178/24640471/0514fe80-18ac-11e7-8eea-879a8cae1abd.png)

**Comment by almccon** [comment]
That's for Site EUI, so the histogram _should_ look like this:
![screen shot 2017-04-03 at 3 apr 8 28 31](https://cloud.githubusercontent.com/assets/1212178/24640497/2d9937fe-18ac-11e7-9c5f-65a8b4a26d55.png)
...not sure why it looks a little different.

Also note, that the averages fro Supermarket and Laboratory are greater than the arbitrary cut-off value of 200 that we're using on the current site.

**Comment by almccon** [comment]
If it's not obvious, the `^` in my visualization marks where along the number line the averages fall, and they're all correctly aligned with the histogram at the top.

**Comment by nicolettehayes** [comment]
this is great, thanks alan.
