### ISSUE TITLE
Footer links and text 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#7]
They probably won't add their own so let's put a placeholder of copyright on it and move on 
For 2016 use current year code 
Use: 
  © Copyright 1995-2016 City of Seattle

**Comment by almccon** [comment]
In lieu of the #17 footer, or does this go somewhere else?

**Comment by almccon** [comment]
<img width="1174" alt="screen shot 2016-12-14 at 14 dec 4 19 00" src="https://cloud.githubusercontent.com/assets/1212178/21206821/2fef53e2-c219-11e6-9a4f-3036f971c838.png">
