### ISSUE TITLE
add an arrow to the building comparison bar

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#74]
when building comparison bar is collapsed, it should have an arrow pointing up, when it's expanded it should have an arrow pointing down.

so
![screen shot 2017-07-25 at 5 02 09 pm](https://user-images.githubusercontent.com/12550451/28598835-2af2c634-715b-11e7-9cd9-17ca8d5bf944.png)
![screen shot 2017-07-25 at 5 02 23 pm](https://user-images.githubusercontent.com/12550451/28598836-2b0d2b6e-715b-11e7-9937-a6fe24fe1fd1.png)

instead of
![screen shot 2017-07-25 at 5 02 33 pm](https://user-images.githubusercontent.com/12550451/28598846-3350404a-715b-11e7-9baa-ccaa3eb3d728.png)
![screen shot 2017-07-25 at 5 02 39 pm](https://user-images.githubusercontent.com/12550451/28598845-334e47b8-715b-11e7-983a-59bed21c0563.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/28796423-79371e94-760b-11e7-8f7a-11f74c2b057a.png)

![image](https://user-images.githubusercontent.com/565486/28796436-80f3a878-760b-11e7-852c-ebadd56143d5.png)
