### ISSUE TITLE
Building comparison bar should be "Seattle Blue"

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#75]
![screen shot 2017-07-25 at 5 05 10 pm](https://user-images.githubusercontent.com/12550451/28598878-71cc50b6-715b-11e7-802a-45331d611975.png)

both blues should be #0047ba

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/28680017-0761ee52-72c3-11e7-9ea8-75e5df25babf.png)
