### ISSUE TITLE
Apply visual design to top of the side bar

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#76]
so this

![screen shot 2017-07-25 at 5 06 58 pm](https://user-images.githubusercontent.com/12550451/28598926-b7fab19a-715b-11e7-8a44-430fad9e1d13.png)

should be this

![screen shot 2017-07-25 at 5 06 29 pm](https://user-images.githubusercontent.com/12550451/28598914-a5356b04-715b-11e7-942f-a5b18dfd9966.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/28680073-2f332ef0-72c3-11e7-902a-9cec0416ef13.png)
