### ISSUE TITLE
Fuel Use chart cuts off

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#80]
Steam gets cut off. Both the label and the value.

![screen shot 2017-07-25 at 5 19 53 pm](https://user-images.githubusercontent.com/12550451/28599199-9081f842-715d-11e7-8d30-2e169cb76790.png)

**Comment by sconnelley** [comment]
I am hiding bar values if there isn't enough room

![image](https://user-images.githubusercontent.com/565486/28832515-ade80ad2-76aa-11e7-9ce2-f96ebdc6a939.png)
