### ISSUE TITLE
Yellow on grey 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#83]
![image](https://user-images.githubusercontent.com/824082/28735614-ee0b7d8c-739a-11e7-8a02-66adb8492449.png)

**Comment by nicolettehayes** [comment]
Change all pop-ups to have #e4e4e4 as background.

![screen shot 2017-07-31 at 11 50 54 am](https://user-images.githubusercontent.com/12550451/28793034-897c9b78-75e6-11e7-9d1b-178b256af1d5.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/28796539-f2662670-760b-11e7-9fee-0e703992a565.png)
