### ISSUE TITLE
energy star score in building popups

### ISSUE THREAD

**Issue by nicolettehayes** [cityenergyproject/seattle#84]
2 problems here: 

- [ ] change the bar to Seattle blue (and the box stroke as well)
- [x] what to do when there is no score... suppress the bar entirely? leave it empty and put N/A? let's ask the client their preference.

![screen shot 2017-07-31 at 11 54 27 am](https://user-images.githubusercontent.com/12550451/28793179-0525f68e-75e7-11e7-9f76-79774aff502e.png)

**Comment by nicolettehayes** [comment]
oops, the client already has addressed the second item:
![screen shot 2017-07-31 at 12 35 08 pm](https://user-images.githubusercontent.com/12550451/28794864-b5716fc8-75ec-11e7-99c1-d4d45e6a6f00.png)

So let's suppress it.

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/29438823-2145832c-836e-11e7-94bb-a7d993d96708.png)
