### ISSUE TITLE
Compare screen overlays bug 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#85]
On Jim's mac, comparison screen is stripey with the map showing in some sections upon scroll. (needs screenshot)

Building Comparison "Drawer” not working in Firefox. Worked fine in Chrome

![image](https://user-images.githubusercontent.com/824082/29236188-19a78266-7ebc-11e7-8c83-655711c2232a.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/29437581-3dc35a18-8366-11e7-9cc9-aba0fae11528.png)
