### ISSUE TITLE
Year Built Distribution incorrect

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#91]
See our current map for correct range (below): 

![image](https://user-images.githubusercontent.com/824082/29236328-f8367bee-7ebd-11e7-926b-000004c18c2e.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/29438299-9f1c62ec-836a-11e7-93a5-36d08a91cc0b.png)
