### ISSUE TITLE
distribution range for Site Total Energy Use

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#92]
The distribution range for Site Total Energy Use is also not set – it is 10 to 100. Please set the range from 0 to 1,000,000 kBtu and see how that looks.

**Comment by sconnelley** [comment]
0 to 1,000,000 didn't look to good.  The median value 1,790,118, so I ended up setting it to 1,000 to 3,000,000 and it looks like this: 
![image](https://user-images.githubusercontent.com/565486/29437787-a4c993ac-8367-11e7-9dad-a266f75f7f38.png)
