### ISSUE TITLE
Building detail text size 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#95]
Some of the text seems too small. Make larger?

**Comment by sconnelley** [comment]
@emilyhobson -- I need a little more to go on here

**Comment by nicolettehayes** [comment]
My vote is to increase the text size for this description:

![28794002-b5b91952-75e9-11e7-924e-82ac36ea0a85](https://user-images.githubusercontent.com/12550451/29540426-26a295ea-8683-11e7-828c-83f9817d197f.png)

I upped the tiny text to 0.8rems and it made the Energy Star Score text _barely_ fit, but with some text editing it would be fine.

![screen shot 2017-08-21 at 3 14 02 pm](https://user-images.githubusercontent.com/12550451/29540546-c227c792-8683-11e7-9dd8-5f259cac94ac.png)
![screen shot 2017-08-21 at 3 15 22 pm](https://user-images.githubusercontent.com/12550451/29540548-c4296d52-8683-11e7-873b-6bc438a13551.png)
