### ISSUE TITLE
Building report text overlap

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#96]
In a few places:

![image](https://user-images.githubusercontent.com/824082/29236549-e26b15a6-7ec0-11e7-865e-459eddd03eff.png)

![image](https://user-images.githubusercontent.com/824082/29236485-c0f280b8-7ebf-11e7-852c-84468424c8cb.png)

https://cityenergyproject.github.io/seattle/#seattle/2016?filters[0][field]=energy_star_score&filters[0][max]=22&filters[1][field]=site_eui&filters[1][max]=31&layer=site_eui&sort=site_eui&order=desc&lat=47.62654&lng=-122.33345&zoom=15&building=560&report_active=true

**Comment by nicolettehayes** [comment]
Okay, I have some new designs that seem to alleviate this issue. But they rely on a couple of principles:

1) selected building stats appear as-is (unchanged) with the blue circle and left-aligned label.
2) building average appears with NO leader line, flush with the top of the corresponding bar
a) if the average is less than the selected building value, label for average aligns right against the left side of the bar. 
b)if the average is greater than the selected building value, label for average aligns left against the right side of the bar.
c) (should be rare) if the building average bar is too short for all the lines of text, the label will sit flush with the bottom of the graph
d) (should be rare) if the building average bar is the furthest to the left, the y-axis will push over to accommodate the text.
3) building average text AND bar should render at 50% opacity
4) if the selected building and the average building occupy the same bar of data, the bar color should render at 100%, but both labels should still appear attached to that bar.

Examples of 2a
![screen shot 2017-08-21 at 1 44 11 pm](https://user-images.githubusercontent.com/12550451/29537506-dd9cccf0-8676-11e7-92aa-c87b5e5713aa.png)

Examples of 2b
![screen shot 2017-08-21 at 1 42 40 pm](https://user-images.githubusercontent.com/12550451/29537461-acd921ea-8676-11e7-8a38-95aa1db2abaf.png)

Example of 2c (DO NOT implement unless we find an actual case of this happening!)
![screen shot 2017-08-21 at 1 49 10 pm](https://user-images.githubusercontent.com/12550451/29537705-8f3c5ea8-8677-11e7-8f3c-8de474f04ae7.png)

Example of 2d (DO NOT implement unless we find an actual case of this happening!)
![screen shot 2017-08-21 at 1 49 57 pm](https://user-images.githubusercontent.com/12550451/29537729-a5c6e81e-8677-11e7-86f3-d7f2836c2cca.png)

Examples of 4
![screen shot 2017-08-21 at 1 52 07 pm](https://user-images.githubusercontent.com/12550451/29537822-01d8a98a-8678-11e7-973d-e7919dbd22cb.png)

**Comment by nicolettehayes** [comment]
For the Fuel Use overlap, I don't have anything very sophisticated (designwise) in mind, except to allow the text to spill over onto the adjacent bar (instead of off the edge of the graph entirely)

So this:
![screen shot 2017-08-21 at 2 54 02 pm](https://user-images.githubusercontent.com/12550451/29539873-a555c400-8680-11e7-9afb-190af128bb9a.png)

Becomes this:
![screen shot 2017-08-21 at 2 51 41 pm](https://user-images.githubusercontent.com/12550451/29539829-759c83ca-8680-11e7-81f2-0290feef8eb2.png)
