### ISSUE TITLE
Building Report: EUI average decimel places 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#98]
The number of decimals for EUI values changes a lot. Let's keep at one decimal place for all – please advise if I should just handle this is preparing data on my end

![image](https://user-images.githubusercontent.com/824082/29236520-4a302740-7ec0-11e7-9160-78c78139ac6a.png)

**Comment by sconnelley** [comment]
![image](https://user-images.githubusercontent.com/565486/29498918-7b834b46-85ba-11e7-926f-e62fe814f18a.png)
