### ISSUE TITLE
Text collision in change from last year 

### ISSUE THREAD

**Issue by emilyhobson** [cityenergyproject/seattle#99]
![image](https://user-images.githubusercontent.com/824082/29236573-37659d9c-7ec1-11e7-9aae-fc509bfca2c4.png)

 See ID 659 for an example.

**Comment by nicolettehayes** [comment]
Looks like the labels are being force directed without regard for value? (In the ID 659 example, the labels are now reversed for the 2015 dots)

![screen shot 2017-08-28 at 10 44 12 am](https://user-images.githubusercontent.com/12550451/29785881-ff9e6004-8bdd-11e7-9122-ff16dc3d3dc9.png)
